return {
  clojure = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = ";;",
    file_ending = "cljs",
  },
  lua = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "#",
    file_ending = "lua",
  },
  sqlite = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "--",
    file_ending = "sql",
  },
  zsh = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "#",
    file_ending = "zsh",
  },
  bash = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "#",
    file_ending = "sh",
  },
  nu = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "#",
    file_ending = "nu",
  },
  python = {
    block_delimiter_start = "%cpaste -q\n",
    block_delimiter_end = "--\n",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "#",
    file_ending = "py",
  },
  bq = {
    block_delimiter_start = "bq query --nouse_legacy_sql '",
    block_delimiter_end = "'",
    newline_delimiter = "",
    line_delimiter_start = "bq query --nouse_legacy_sql '",
    line_delimiter_end = "'",
    comment_character = "--",
    file_ending = "zsh",
  },
  lq = {
    block_delimiter_start = "lq sq '",
    block_delimiter_end = "'",
    newline_delimiter = "",
    line_delimiter_start = "lq sq '",
    line_delimiter_end = "'",
    comment_character = ";;",
    file_ending = "zsh",
  },
  sql = {
    block_delimiter_start = "",
    block_delimiter_end = "",
    newline_delimiter = "",
    line_delimiter_start = "",
    line_delimiter_end = "",
    comment_character = "--",
    file_ending = "sql",
  },
}
