return {
  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      "onsails/lspkind-nvim",
    },
    opts = function(_, opts)
      opts.formatting = opts.formatting or {}
      opts.formatting.format = require("lspkind").cmp_format {
        mode = "symbol",
        symbol_map = {
          Copilot = "",
          Codeium = "",
        },
      }
    end,
  },
  {
    "onsails/lspkind.nvim",
    opts = {
      mode = "symbol_text",
      symbol_map = {
        Copilot = "",
        Codeium = "",
        --   Text = "",
        --   Method = "",
        --   Function = "",
        --   Constructor = "",
        --   Field = "ﰠ",
        --   Variable = "",
        --   Class = "ﴯ",
        --   Interface = "",
        --   Module = "",
        --   Property = "ﰠ",
        --   Unit = "塞",
        --   Value = "",
        --   Enum = "",
        --   Keyword = "",
        --   Snippet = "",
        --   Color = "",
        --   File = "",
        --   Reference = "",
        --   Folder = "",
        --   EnumMember = "",
        --   Constant = "",
        --   Struct = "פּ",
        --   Event = "",
        --   Operator = "",
        --   TypeParameter = "",
        -- Text = "",
        -- Method = "",
        -- Function = "",
        -- Constructor = "",
        -- Field = "ﴲ",
        -- Variable = "]",
        -- Class = "",
        -- Interface = "ﰮ",
        -- Module = "",
        -- Property = "襁",
        -- Unit = "",
        -- Value = "",
        -- Enum = "練",
        -- Keyword = "",
        -- Snippet = "",
        -- Color = "",
        -- File = "",
        -- Reference = "",
        -- Folder = "",
        -- EnumMember = "",
        -- Constant = "ﲀ",
        -- Struct = "ﳤ",
        -- Event = "",
        -- Operator = "",
        -- TypeParameter = "",
      },
    },
    config = function(_, opts) require("lspkind").init(opts) end,
  },
  {
    "projekt0n/circles.nvim",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = {},
  },
  { "mortepau/codicons.nvim" },
}
